### ISSUE TITLE
[Bug] BetterRTP Hook issue

### ISSUE THREAD

**Issue by Kedarin** [timderspieler/DeluxeCombat-Issues#53]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

1.8.8

### Your discord name

Kedarin#0738

### Current Behavior

[19:15:14 INFO]: Kedarin issued server command: /rtp
[19:15:14 ERROR]: Could not pass event RTP_TeleportPreEvent to DeluxeCombat v1.40.4
java.lang.NoSuchMethodError: me.SuperRonanCraft.BetterRTP.references.customEvents.RTP_TeleportPreEvent.getPlayer()Lorg/bukkit/entity/Player;
        at nl.marido.deluxecombat.hooks.plugins.commonhook.BetterRTPHook.onRandomCommand(BetterRTPHook.java:89) ~[?:?]
        at org.imanity.imanityspigot.events.executor.asm.generated.GeneratedEventExecutor485.execute(Unknown Source) ~[?:?]
        at org.imanity.imanityspigot.executor.EventExecutorGenerator.lambda$create$1(EventExecutorGenerator.java:62) ~[spigot.jar:git-iSpigot-PaperEdition]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:521) ~[spigot.jar:git-iSpigot-PaperEdition]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:507) ~[spigot.jar:git-iSpigot-PaperEdition]
        at me.SuperRonanCraft.BetterRTP.player.rtp.RTPTeleport.beforeTeleportInstant(RTPTeleport.java:88) ~[?:?]

### Expected Behavior

error using /rtp 

### Steps To Reproduce

Install deluxecombat
Install BetterRTP
Use /rtp

### Frequency

100%

**Comment by Kedarin** [comment]
Oh, I didn't use the latest version of DeluxeCombat because it's java 16 and I am running 1.8.8 so I use 1.40.4

**Comment by timderspieler** [comment]
DeluxeCombat 1.40.6 should be compatible with Java 8 again, can you please test that?
