### ISSUE TITLE
Addon Update Issue

### ISSUE THREAD

**Issue by 00Hrtz** [timderspieler/DeluxeCombat-Issues#58]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Unable to update the essentialsx addon from 1.0.0 to 1.0.1. although says it was removed in chat and installed after on screen.
![2023-05-09](https://github.com/timderspieler/DeluxeCombat-Issues/assets/66942713/fe55f078-50c5-4c2e-ad98-f67bee8fd37c)

### Your discord name

sircraftypants#4875

### Current Behavior

unable to update addon

### Expected Behavior

update the addon

### Steps To Reproduce

click on the tab essentialsx addon update tab in the menu

### Frequency

100%

**Comment by timderspieler** [comment]
Addon has been updated! Thank you for your report :)
Please simply re-download the Essentials Addon update.

**Comment by 00Hrtz** [comment]
when clicking on marketplace and installed addons

`[18:21:30 ERROR]: Could not pass event InventoryClickEvent to DeluxeCombat v1.40.7
java.lang.NullPointerException: Cannot invoke "nl.marido.deluxecombat.objects.addons.MarketPlaceItem.isVerified()" because the return value of "java.util.HashMap.get(Object)" is null
        at nl.marido.deluxecombat.hooks.addonstore.AddonManager.buildAddonItem(AddonManager.java:379) ~[DeluxeCombat v.1.40.7.jar:?]
        at nl.marido.deluxecombat.hooks.addonstore.AddonManager.lambda$getInstalledAddonItems$3(AddonManager.java:401) ~[DeluxeCombat v.1.40.7.jar:?]
        at java.util.HashMap$KeySet.forEach(HashMap.java:1008) ~[?:?]
        at nl.marido.deluxecombat.hooks.addonstore.AddonManager.getInstalledAddonItems(AddonManager.java:401) ~[DeluxeCombat v.1.40.7.jar:?]
        at nl.marido.deluxecombat.inventories.AddonsInventory.openInstalledAddons(AddonsInventory.java:56) ~[DeluxeCombat v.1.40.7.jar:?]
        at nl.marido.deluxecombat.listeners.DeluxeInventoryListener.onAddonMenuClick(DeluxeInventoryListener.java:474) ~[DeluxeCombat v.1.40.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1125.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-530]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-530]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-530]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3196) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-530]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-530]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-530]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-530]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-530]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-530]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-530]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-530]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by 00Hrtz** [comment]
also this 

`[19:27:21 ERROR]: [DeluxeCombat] An error occurred while fetching the addon marketplace data! Please report this to the author: no protocol: ️`
