### ISSUE TITLE
[Bug]  Error on changing worldguard border material

### ISSUE THREAD

**Issue by MatinHQ** [timderspieler/DeluxeCombat-Issues#67]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Purpur 1.19.4

### Your discord name

Matin#2511

### Current Behavior

Plugin throws a error when you try to change worldguard border maetial

### Expected Behavior

It should not throw error

### Steps To Reproduce

1. /dc menu
2. select supported plugins
3. select world guard
4. select changing border materials
5. select a material

### Frequency

It happens 100% of the time

### Anything else?

```
[12:29:17 ERROR]: Could not pass event InventoryClickEvent to DeluxeCombat v1.40.8
java.lang.NullPointerException: Cannot invoke "nl.marido.deluxecombat.utils.tuple.Pair.getLeft()" because the return value of "java.util.Map.get(Object)" is null
        at nl.marido.deluxecombat.inventories.SelectorInventoryUtils.onSelectorInventoryClick(SelectorInventoryUtils.java:224) ~[DeluxeCombat v.1.40.8.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1066.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1968]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3286) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1968]
        at net.minecraft.server.MinecraftServer.lambda$spi
        ```

**Comment by MatinHQ** [comment]
Some how it's working fine now, however it might worth a look to that error so it won't happen later, feel free to close the issue

**Comment by timderspieler** [comment]
Okay. Thank you for your report. I have changed some lines internally that should prevent this error from appearing again. Thank you very much for your report!
