### ISSUE TITLE
[Bug] onPacketSending(PacketEvent)

### ISSUE THREAD

**Issue by Royul2k** [timderspieler/DeluxeCombat-Issues#71]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [x] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Pufferfish+ (Purpur) 1.19.4

### Your discord name

Roslyn#5632

### Current Behavior

I'm getting an error in console when I open a menu with custom sounds enabled (itemsadder) 

**It's only when I enable the "ProtocolLib" disable sound feature.**

I only have four sounds added to the list

- ENTITY_PLAYER_ATTACK_KNOCKBACK
- ENTITY_PLAYER_ATTACK_SWEEP
- ENTITY_PLAYER_ATTACK_NODAMAGE
- ENTITY_PLAYER_ATTACK_STRONG

### Expected Behavior

No console error.

### Steps To Reproduce

Enable Disable Sounds with ProtocolLib & have a custom sound play. 

### Frequency

Everytime the custom sound plays.

### Anything else?

`[15:08:46 ERROR]: [DeluxeCombat] Unhandled exception occurred in onPacketSending(PacketEvent) for DeluxeCombat
java.lang.NullPointerException: Cannot match XSound of a null sound
        at java.util.Objects.requireNonNull(Objects.java:235) ~[?:?]
        at nl.marido.deluxecombat.shaded.xseries.XSound.matchXSound(XSound.java:1654) ~[DeluxeCombat v.1.50.1.jar:?]
        at nl.marido.deluxecombat.hooks.protocollib.nosounds.NoSoundListener.protocolSound(NoSoundListener.java:50) ~[DeluxeCombat v.1.50.1.jar:?]
        at nl.marido.deluxecombat.hooks.protocollib.nosounds.NoSoundListener$1.onPacketSending(NoSoundListener.java:26) ~[DeluxeCombat v.1.50.1.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:555) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:528) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:566) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:467) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java) ~[?:?]
        at net.minecraft.network.Connection.a(Connection.java) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.a(ServerGamePacketListenerImpl.java) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.a(ServerGamePacketListenerImpl.java) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.playSound() ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.playSound() ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.brcdev.shopgui.sound.SoundManager.playSound(SoundManager.java:79) ~[ShopGUIPlus-1.85.0.jar:?]
        at net.brcdev.shopgui.shop.ShopManager$1.onSuccess(ShopManager.java:102) ~[ShopGUIPlus-1.85.0.jar:?]
        at net.brcdev.shopgui.shop.ShopManager$1.onSuccess(ShopManager.java:98) ~[ShopGUIPlus-1.85.0.jar:?]
        at net.brcdev.shopgui.player.PlayerManager.handlePlayerData(PlayerManager.java:76) ~[ShopGUIPlus-1.85.0.jar:?]
        at net.brcdev.shopgui.shop.ShopManager.openMainMenu(ShopManager.java:98) ~[ShopGUIPlus-1.85.0.jar:?]
        at net.brcdev.shopgui.shop.ShopManager.openMainMenu(ShopManager.java:89) ~[ShopGUIPlus-1.85.0.jar:?]
        at net.brcdev.shopgui.command.CmdShop.onCommand(CmdShop.java:63) ~[ShopGUIPlus-1.85.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[pufferfishplus-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[pufferfishplus-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand() ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run() ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at com.mojang.brigadier.CommandDispatcher.execute() ~[pufferfishplus-1.19.4.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java) ~[?:?]
        at net.minecraft.commands.Commands.a(Commands.java) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.a(ServerGamePacketListenerImpl.java) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$22(ServerGamePacketListenerImpl.java) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.b(BlockableEventLoop.java) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.util.thread.BlockableEventLoop.d(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.d(ReentrantBlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.util.thread.BlockableEventLoop.x(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.util.thread.BlockableEventLoop.c(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java) ~[pufferfishplus-1.19.4.jar:git-PufferfishPlusPurpur-19]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:08:46 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutNamedSoundEffect@b33b42[
    b=Direct{net.minecraft.sounds.SoundEffect@250668e4}
    c=MASTER
    d=-101
    e=1112
    f=-75
    g=0.2
    h=1.0
    i=-2575608284450540118
  ]`

**Comment by timderspieler** [comment]
Thank you for the report @Royul2k ! The issues has been fixed ( https://github.com/timderspieler/DeluxeCombat/commit/bc19de6bbeb2fa8afc31af4f6b5fd9ba68ef7d79 ) and will be part of the next upcoming update!
