### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by xProMDFKx** [timderspieler/DeluxeCombat-Issues#72]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Light Spigot latest version

### Your discord name

skir.tty

### Current Behavior

I keep getting an error since I switched to version 1.20.1 and I saw that other users of the plugin get the same error:

[15:52:44 ERROR]: Could not pass event PlayerDeathEvent to DeluxeCombat v1.50.1
java.lang.IllegalArgumentException: UUID id cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.getPlayer(CraftServer.java:634) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at org.bukkit.Bukkit.getPlayer(Bukkit.java:722) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at nl.marido.deluxecombat.utils.DeathLogic.getDeathMessage(DeathLogic.java:388) ~[DeluxeCombat v.1.50.1.jar:?]
        at nl.marido.deluxecombat.listeners.DeathListener.compute(DeathListener.java:236) ~[DeluxeCombat v.1.50.1.jar:?]
        at nl.marido.deluxecombat.listeners.DeathListener.playerDeath(DeathListener.java:83) ~[DeluxeCombat v.1.50.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor971.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:git-LightSpigot-"186942d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:925) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:964) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1537) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:967) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1133) ~[?:?]
        at net.minecraft.world.entity.item.FallingBlockEntity.lambda$causeFallDamage$1(FallingBlockEntity.java:297) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at net.minecraft.world.entity.item.FallingBlockEntity.causeFallDamage(FallingBlockEntity.java:295) ~[?:?]
        at net.minecraft.world.level.block.Block.fallOn(Block.java:444) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.world.entity.Entity.checkFallDamage(Entity.java:1766) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.world.entity.Entity.move(Entity.java:1150) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.world.entity.item.FallingBlockEntity.tick(FallingBlockEntity.java:148) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1368) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:874) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:852) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1557) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1408) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Expected Behavior

To not get those errors

### Steps To Reproduce

1. Start the server
2. Just punch a player

### Frequency

Minute by minute

### Anything else?

[15:56:21 ERROR]: Could not pass event PlayerDeathEvent to DeluxeCombat v1.50.1
java.lang.IllegalArgumentException: UUID id cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.getPlayer(CraftServer.java:634) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at org.bukkit.Bukkit.getPlayer(Bukkit.java:722) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at nl.marido.deluxecombat.utils.DeathLogic.getDeathMessage(DeathLogic.java:388) ~[DeluxeCombat v.1.50.1.jar:?]
        at nl.marido.deluxecombat.listeners.DeathListener.compute(DeathListener.java:236) ~[DeluxeCombat v.1.50.1.jar:?]
        at nl.marido.deluxecombat.listeners.DeathListener.playerDeath(DeathListener.java:83) ~[DeluxeCombat v.1.50.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor971.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:git-LightSpigot-"186942d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[lightspigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:925) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:964) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1537) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:967) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1133) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.causeFallDamage(LivingEntity.java:2045) ~[?:?]
        at net.minecraft.world.entity.player.Player.causeFallDamage(Player.java:1769) ~[?:?]
        at net.minecraft.world.level.block.Block.fallOn(Block.java:444) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.world.entity.Entity.checkFallDamage(Entity.java:1766) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.world.entity.LivingEntity.checkFallDamage(LivingEntity.java:387) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doCheckFallDamage(ServerPlayer.java:1536) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1638) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:88) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1353) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:200) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1330) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1323) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1301) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1189) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[lightspigot-1.20.1.jar:git-LightSpigot-"186942d"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by timderspieler** [comment]
Issue has been fixed in v.1.50.2. Thank you for your report!
