### ISSUE TITLE
[Bug] Update shaded dependency XSeries

### ISSUE THREAD

**Issue by EuSouVoce** [timderspieler/DeluxeCombat-Issues#84]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

Purpur 1.20.6

### Your discord name

eusouvoce

### Current Behavior

As with the usage of the mojang mappings, the package ``org.bukkit.craftbukkit`` **does not** uses the semantic versioning in the package name.

The plugin fails to start.

### Expected Behavior

Successful plugin startup

### Steps To Reproduce

Download latest paper or paper forks for 1.20.6
Install DeluxeCombat on the plugins folder
start server
check logs.

### Frequency

100% of the time, it's a reflection issue.

### Anything else?

```ps
[08:59:15] [Server thread/ERROR]: Error occurred while enabling DeluxeCombat v1.60.4 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at DeluxeCombat v.1.60.4.jar/nl.marido.deluxecombat.shaded.xseries.SkullUtils.<clinit>(SkullUtils.java:83) ~[DeluxeCombat v.1.60.4.jar:?]
	at DeluxeCombat v.1.60.4.jar/nl.marido.deluxecombat.ItemUtils.buildSkullFromHash(ItemUtils.java:196) ~[DeluxeCombat v.1.60.4.jar:?]
	at DeluxeCombat v.1.60.4.jar/nl.marido.deluxecombat.ItemUtils.buildHeadDB(ItemUtils.java:240) ~[DeluxeCombat v.1.60.4.jar:?]
	at DeluxeCombat v.1.60.4.jar/nl.marido.deluxecombat.Settings.loadInventories(Settings.java:1288) ~[DeluxeCombat v.1.60.4.jar:?]
	at DeluxeCombat v.1.60.4.jar/nl.marido.deluxecombat.Settings.<init>(Settings.java:189) ~[DeluxeCombat v.1.60.4.jar:?]
	at DeluxeCombat v.1.60.4.jar/nl.marido.deluxecombat.DeluxeCombat.onEnable(DeluxeCombat.java:144) ~[DeluxeCombat v.1.60.4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.20.6.jar:git-Purpur-2207]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:git-Purpur-2207]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:623) ~[purpur-1.20.6.jar:git-Purpur-2207]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:572) ~[purpur-1.20.6.jar:git-Purpur-2207]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:684) ~[purpur-1.20.6.jar:git-Purpur-2207]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:443) ~[purpur-1.20.6.jar:git-Purpur-2207]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:357) ~[purpur-1.20.6.jar:git-Purpur-2207]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[purpur-1.20.6.jar:git-Purpur-2207]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[purpur-1.20.6.jar:git-Purpur-2207]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Failed to parse server version. Could not find any package starting with name: 'org.bukkit.craftbukkit.v'
	at DeluxeCombat v.1.60.4.jar/nl.marido.deluxecombat.shaded.xseries.ReflectionUtils.<clinit>(ReflectionUtils.java:95) ~[DeluxeCombat v.1.60.4.jar:?]
	... 18 more
[08:59:15] [Server thread/INFO]: [DeluxeCombat] Disabling DeluxeCombat v1.60.4
```

**Comment by timderspieler** [comment]
Hello @EuSouVoce ,
thank you for the report. I have added support for minecraft v.1.20.6 with the latest version of DeluxeCombat which has been released yesterday. (v.1.60.5)

Thank you very much for your patience.
