### ISSUE TITLE
[Bug] Combat Tag doesn't works on 1.8.8

### ISSUE THREAD

**Issue by IceGames23** [timderspieler/DeluxeCombat-Issues#85]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

PandaSpigot v119 (Paper's 1.8.8 fork)

### Your discord name

icegames

### Current Behavior

I just bought the plugin, configured the things, and when I test the combat with others players the combattag doesn't works and appers a error on console for each hit.

### Expected Behavior

Works normally and the combat tag works

### Steps To Reproduce

Hit other player, for entities (PvE) the combattag works

### Frequency

100% of the time

### Anything else?

The error that floods for each hit in other players
`[02:43:57 ERROR]: Could not pass event EntityDamageByEntityEvent to DeluxeCombat v1.60.5
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:564) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:549) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:557) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:470) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:589) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1117) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:860) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:748) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:801) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:512) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1010) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1099) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1406) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:34) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:5) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(PlayerConnectionUtils.java:9) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:11) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:881) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:412) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:815) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:648) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.AbstractMethodError: Receiver class me.ulrich.clans.eFgH5.eFgH5.aB2cD3 does not define or inherit an implementation of the resolved method 'abstract boolean canCombat(org.bukkit.entity.Player, org.bukkit.entity.Player)' of abstract class nl.marido.deluxecombat.hooks.template.CombatHook.
        at nl.marido.deluxecombat.utils.CombatUtils.canCombat(CombatUtils.java:458) ~[?:?]
        at nl.marido.deluxecombat.listeners.HitListener.combatListener(HitListener.java:129) ~[?:?]
        at nl.marido.deluxecombat.listeners.HitListener.hitHighest(HitListener.java:83) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PandaSpigot-119]
        ... 28 more`

**Comment by timderspieler** [comment]
Hey @IceGames23 ,

thank you for reaching out to me!

The issue seems to be UltimateClans here: _Receiver class me.ulrich.clans.eFgH5.eFgH5.aB2cD3 does not define or inherit an implementation of the resolved method 'abstract boolean canCombat(org.bukkit.entity.Player, org.bukkit.entity.Player)' of abstract class_

Please contact the author of UltimateClans regarding this issue :)

greetings
Tim

**Comment by IceGames23** [comment]
@timderspieler 
[error.txt](https://github.com/user-attachments/files/16091912/error.txt)
Now this error appers when a player dies, I'm using the leatest version
