### ISSUE TITLE
[latest BUG!] java.lang.OutOfMemoryError 

### ISSUE THREAD

**Issue by GG-MD** [timderspieler/DeluxeCombat-Issues#89]

**Comment by timderspieler** [comment]
Hello @GG-MD !
This error is caused by JVM flags. Can you please tell me which ones you are using?

**Comment by GG-MD** [comment]
> Hello @GG-MD !
> 
> This error is caused by JVM flags. Can you please tell me which ones you are using?

```

aikar_jvm_flags="-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+DisableExplicitGC -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:+UseLoopPredicate -XX:+RangeCheckElimination -XX:+EliminateLocks -XX:+DoEscapeAnalysis -XX:+UseCodeCacheFlushing -XX:+SegmentedCodeCache -XX:+UseFastJNIAccessors -XX:+OptimizeStringConcat -XX:+UseCompressedOops -XX:+TrustFinalNonStaticFields -XX:+UseInlineCaches -XX:+RewriteBytecodes -XX:+RewriteFrequentPairs -XX:+UseNUMA -XX:+OptimizeFill -XX:+UseVectorCmov -XX:+ScavengeBeforeFullGC -XX:+UseNewLongLShift -XX:+UseFastUnorderedTimeStamps"
jvm_flags="-Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dfile.encoding=UTF-8 -Dlog4j2.formatMsgNoLookups=true -DPaper.IgnoreJavaVersion=true -Dnet.kyori.ansi.colorLevel=indexed256 -server"

```

**Comment by GG-MD** [comment]
This didn't happen before upgrading to the latest version of the plugin, the flags are the same, the problem must be yours.

**Comment by timderspieler** [comment]
Could you still please provide me your flags? I try to narrow down the issue.

**Comment by GG-MD** [comment]
> Could you still please provide me your flags? I try to narrow down the issue. 

Read above comments !

**Comment by GG-MD** [comment]
@timderspieler 
**This appeared again after moving to a new dedicated server.!!!!**
_I'm guessing this is a one-time bug when I moved to other servers. Very strange._


```
[09:48:32] [Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PURPUR - THIS IS NOT A BUG OR A CRASH  - 1.21.1-2304-dee41bc (MC: 1.21.1) ---
[09:48:32] [Watchdog Thread/ERROR]: The server has not responded for 7 seconds! Creating thread dump
[09:48:32] [Watchdog Thread/ERROR]: ------------------------------
[09:48:32] [Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Purpur!):
[09:48:32] [Watchdog Thread/ERROR]: ------------------------------
[09:48:32] [Watchdog Thread/ERROR]: Current Thread: Server thread
[09:48:32] [Watchdog Thread/ERROR]: 	PID: 115 | Suspended: false | Native: false | State: RUNNABLE
[09:48:32] [Watchdog Thread/ERROR]: 	Stack:
[09:48:32] [Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.entity.CraftEntity.getUniqueId(CraftEntity.java:509)
[09:48:32] [Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.entity.CraftPlayer.canSee(CraftPlayer.java:2258)
[09:48:32] [Watchdog Thread/ERROR]: 		net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:1265)
[09:48:32] [Watchdog Thread/ERROR]: 		net.minecraft.server.level.ChunkMap$TrackedEntity.moonrise$tick(ChunkMap.java:1137)
[09:48:32] [Watchdog Thread/ERROR]: 		net.minecraft.server.level.ChunkMap.newTrackerTick(ChunkMap.java:934)
[09:48:32] [Watchdog Thread/ERROR]: 		net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:956)
[09:48:32] [Watchdog Thread/ERROR]: 		net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:413)
[09:48:32] [Watchdog Thread/ERROR]: 		net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:710)
[09:48:32] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1844)
[09:48:32] [Watchdog Thread/ERROR]: 		net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513)
[09:48:32] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635)
[09:48:32] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1335)
[09:48:32] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334)
[09:48:32] [Watchdog Thread/ERROR]: 		net.minecraft.server.MinecraftServer$$Lambda/0x00007ff8ecce33e8.run(Unknown Source)
[09:48:32] [Watchdog Thread/ERROR]: 		java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596)
[09:48:32] [Watchdog Thread/ERROR]: 		java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)
[09:48:32] [Watchdog Thread/ERROR]: ------------------------------
[09:48:32] [Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PURPUR - THIS IS NOT A BUG OR A CRASH ---
[09:48:32] [Watchdog Thread/ERROR]: ------------------------------
[09:48:39] [Craft Scheduler Thread - 153 - DeluxeCombat/WARN]: [DeluxeCombat] Plugin DeluxeCombat v1.60.7 generated an exception while executing task 112
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.base/java.util.Arrays.copyOf(Arrays.java:3541) ~[?:?]
	at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:242) ~[?:?]
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:587) ~[?:?]
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:179) ~[?:?]
	at DeluxeCombat v.1.60.7.jar/nl.marido.deluxecombat.Settings.getProgressBar(Settings.java:1258) ~[DeluxeCombat v.1.60.7.jar:?]
	at DeluxeCombat v.1.60.7.jar/nl.marido.deluxecombat.objects.Tagger.sendTime(Tagger.java:278) ~[DeluxeCombat v.1.60.7.jar:?]
	at DeluxeCombat v.1.60.7.jar/nl.marido.deluxecombat.tasks.TagTask.run(TagTask.java:36) ~[DeluxeCombat v.1.60.7.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2304-dee41bc]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.1.jar:1.21.1-2304-dee41bc]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.1.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.runWith(Thread.java:1596) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
	```

**Comment by GG-MD** [comment]
_Maybe this will help in some way with the solution._
<img width="874" alt="image" src="https://github.com/user-attachments/assets/b4bba063-d2c2-4fef-9b94-7acf090f0d20">

**Comment by GG-MD** [comment]
> > Hello @GG-MD !
> > This error is caused by JVM flags. Can you please tell me which ones you are using?
> 
> ```
> 
> aikar_jvm_flags="-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+DisableExplicitGC -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:+UseLoopPredicate -XX:+RangeCheckElimination -XX:+EliminateLocks -XX:+DoEscapeAnalysis -XX:+UseCodeCacheFlushing -XX:+SegmentedCodeCache -XX:+UseFastJNIAccessors -XX:+OptimizeStringConcat -XX:+UseCompressedOops -XX:+TrustFinalNonStaticFields -XX:+UseInlineCaches -XX:+RewriteBytecodes -XX:+RewriteFrequentPairs -XX:+UseNUMA -XX:+OptimizeFill -XX:+UseVectorCmov -XX:+ScavengeBeforeFullGC -XX:+UseNewLongLShift -XX:+UseFastUnorderedTimeStamps"
> jvm_flags="-Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dfile.encoding=UTF-8 -Dlog4j2.formatMsgNoLookups=true -DPaper.IgnoreJavaVersion=true -Dnet.kyori.ansi.colorLevel=indexed256 -server"
> ```

and:
<img width="207" alt="image" src="https://github.com/user-attachments/assets/028fe78d-4b60-4817-b441-1b03c19d8f7f">

**Comment by timderspieler** [comment]
I have located the potential issue here. Would you mind testing a dev build of the plugin to check if the issue is gone?

**Comment by GG-MD** [comment]
> I have located the potential issue here. Would you mind testing a dev build of the plugin to check if the issue is gone?

The main thing is that the server did not shut down, otherwise any tests, go)

**Comment by timderspieler** [comment]
I've wrote you a DM on discord.
