### ISSUE TITLE
[DeluxeCombat] Unhandled exception occurred in onPacketSending(PacketEvent) for DeluxeCombat

### ISSUE THREAD

**Issue by danieliustt** [timderspieler/DeluxeCombat-Issues#93]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### DeluxeCombat Version

- [X] I made sure that I am using the latest version of DeluxeCombat

### Server Software / Version

1.21.3 (PufferFish)

### Your discord name

stonegrillo

### Current Behavior

Fix

### Expected Behavior

Fix

### Steps To Reproduce

[14:46:15] [Server thread/ERROR]: [DeluxeCombat] Unhandled exception occurred in onPacketSending(PacketEvent) for DeluxeCombat
java.lang.IllegalStateException: Unable to invoke method public static org.bukkit.Sound org.bukkit.craftbukkit.CraftSound.minecraftToBukkit(net.minecraft.sounds.SoundEvent)
at ProtocolLib.jar/com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:25) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.wrappers.BukkitConverters$20.getSpecific(BukkitConverters.java:1171) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.wrappers.BukkitConverters$20.getSpecific(BukkitConverters.java:1156) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.wrappers.Converters$1.getSpecific(Converters.java:52) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.wrappers.Converters$8.getSpecific(Converters.java:310) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.wrappers.Converters$1.getSpecific(Converters.java:52) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:303) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.reflect.StructureModifier.readSafely(StructureModifier.java:277) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.reflect.StructureModifier.getValues(StructureModifier.java:485) ~[ProtocolLib.jar:?]
at DeluxeCombat v.1.60.9.jar/nl.marido.deluxecombat.hooks.protocollib.nosounds.NoSoundListener.protocolSound(NoSoundListener.java:54) ~[DeluxeCombat v.1.60.9.jar:?]
at DeluxeCombat v.1.60.9.jar/nl.marido.deluxecombat.hooks.protocollib.nosounds.NoSoundListener$1.onPacketSending(NoSoundListener.java:25) ~[DeluxeCombat v.1.60.9.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invokeListener(OutboundPacketListenerSet.java:74) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.injector.collection.PacketListenerSet.lambda$invoke$0(PacketListenerSet.java:123) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.timing.TimingTracker.lambda$static$0(TimingTracker.java:7) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:123) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.injector.collection.OutboundPacketListenerSet.invoke(OutboundPacketListenerSet.java:30) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.injector.collection.PacketListenerSet.invoke(PacketListenerSet.java:102) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:528) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.injector.PacketFilterManager.invokeOutboundPacketListeners(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:528) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:44) ~[ProtocolLib.jar:?]
at ProtocolLib.jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:233) ~[ProtocolLib.jar:?]
at net.minecraft.network.Connection.sendPacket(Connection.java:497) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.network.Connection.send(Connection.java:457) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:320) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:301) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at org.bukkit.craftbukkit.entity.CraftPlayer.playSound0(CraftPlayer.java:840) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at org.bukkit.craftbukkit.entity.CraftPlayer.playSound(CraftPlayer.java:831) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at org.bukkit.craftbukkit.entity.CraftPlayer.playSound(CraftPlayer.java:817) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at org.bukkit.craftbukkit.entity.CraftPlayer.playSound(CraftPlayer.java:807) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at ShopGUIPlus-1.101.0.jar/net.brcdev.shopgui.sound.SoundManager.playSound(SoundManager.java:79) ~[ShopGUIPlus-1.101.0.jar:?]
at ShopGUIPlus-1.101.0.jar/net.brcdev.shopgui.shop.ShopManager.openShopMenu(ShopManager.java:714) ~[ShopGUIPlus-1.101.0.jar:?]
at ShopGUIPlus-1.101.0.jar/net.brcdev.shopgui.listener.PlayerListener.clickAmountSelectionGui(PlayerListener.java:434) ~[ShopGUIPlus-1.101.0.jar:?]
at ShopGUIPlus-1.101.0.jar/net.brcdev.shopgui.listener.PlayerListener.onInventoryClick(PlayerListener.java:143) ~[ShopGUIPlus-1.101.0.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor737.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.21.3-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[pufferfish-api-1.21.3-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.21.3-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[pufferfish-api-1.21.3-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3251) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1584) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:207) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:128) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1561) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1554) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:138) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1505) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1515) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1351) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:341) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Cannot convert 'SoundEvent[location=minecraft:ui.button.click, fixedRange=Optional.empty]' to bukkit representation, since it is not registered.
at org.bukkit.craftbukkit.CraftRegistry.lambda$minecraftToBukkit$0(CraftRegistry.java:97) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
at org.bukkit.craftbukkit.CraftRegistry.minecraftToBukkit(CraftRegistry.java:97) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at org.bukkit.craftbukkit.CraftSound.minecraftToBukkit(CraftSound.java:19) ~[pufferfish-1.21.3.jar:1.21.3-23-784d72f]
at ProtocolLib.jar/com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[ProtocolLib.jar:?]
... 58 more
[14:46:15] [Server thread/ERROR]: Parameters:
net.minecraft.network.protocol.game.ClientboundSoundPacket@3f96cd0e[
sound=Direct{SoundEvent[location=minecraft:ui.button.click, fixedRange=Optional.empty]}
source=MASTER
x=-90921
y=576
z=-54832
volume=0.2
pitch=1.0
seed=-3818158013453198877
]

### Frequency

https://pastebin.com/MigVgaTh

**Comment by timderspieler** [comment]
Has been fixed with v1.70.1!
Thanks for the report!
